### ISSUE TITLE
好久支持md img 图文这几种类型的消息呢

### ISSUE THREAD

**Issue by nondevops** [MakDon/we-work-bot#1]
添加 Markdown 类型消息的支持
 添加 image 类型消息的支持
 添加 图文类型消息的支持

**Comment by MakDon** [comment]
> 添加 Markdown 类型消息的支持
> 添加 image 类型消息的支持
> 添加 图文类型消息的支持

真有人用的话我今晚就可以开始更新了
（怎么有一种被催稿的感觉

**Comment by nondevops** [comment]
那麻烦你更新下吧.我在用,啊哈哈.忠实粉丝.谢谢 @MakDon

**Comment by MakDon** [comment]
非常自豪的宣布整个国庆一行代码没有写过...

**Comment by nondevops** [comment]
啊哈那你真是太棒了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Makdon <notifications@github.com&gt;
发送时间: 2019年10月7日 19:18
收件人: MakDon/we-work-bot <we-work-bot@noreply.github.com&gt;
抄送: nondevops <371918642@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MakDon/we-work-bot] 好久支持md img 图文这几种类型的消息呢 (#1)




非常自豪的宣布整个国庆一行代码没有写过...

**Comment by nondevops** [comment]
> 非常自豪的宣布整个国庆一行代码没有写过...

@MakDon 可以更新吗?期待你的回复

**Comment by MakDon** [comment]
> > 非常自豪的宣布整个国庆一行代码没有写过...
> 
> @MakDon 可以更新吗?期待你的回复

有机会的，只是当社畜之后时间和精力没有那么多了（于是经常不想写代码

**Comment by nondevops** [comment]
> > > 非常自豪的宣布整个国庆一行代码没有写过...
> > 
> > 
> > @MakDon 可以更新吗?期待你的回复
> 
> 有机会的，只是当社畜之后时间和精力没有那么多了（于是经常不想写代码

@MakDon hi,我苦苦等待1个多月了,可以动用下您的小指头上传更新下您的力作么? 么么哒~
