### ISSUE TITLE
如何设置每日定时任务？

### ISSUE THREAD

**Issue by hanzo-genji** [MakDon/we-work-bot#2]
bots.add_bot(url).set_text("every 10 seconds").every(day=1,hour=0,minute=12)

这种写法设置每日定时任务没有生效。。

**Comment by MakDon** [comment]
最后加个 .run() 试试?
才发现 example 里面我也漏掉 run 了...

**Comment by MakDon** [comment]
接上一条:
没漏，只是换了两行不是很明显了
像[这样](https://github.com/MakDon/we-work-bot/blob/master/example.py#L100)

**Comment by MakDon** [comment]
太久没回复，close
